### ISSUE TITLE
Centering the elements

### ISSUE THREAD

**Issue by hend0298** [hend0298/just-your-type#2]
@thomasjbradley I can't seem to center all the elements on the page without messing up the smaller text when resizing the window. Do you know what I could do to fix this?

**Comment by thomasjbradley** [comment]
A few changes will make it work:

1. Add `text-center` onto the `.grid` `<div>`
2. Remove your `left` & `bottom` coordinates from `.absolute`—in fact it’s not good practice to style the Modulifier classes because it breaks expectations of what those classes are doing.
3. Add the class `.pin-c` onto the `<span>` inside the `<h1>`
4. Remove the `.pad-t-2` from the `<h1>` and put it on the `.unit`

**Comment by hend0298** [comment]
That kinda helped but when I make the window larger the whole design still stays stuck to the left instead of being centered. How would I fix that problem?
